module.exports = [
  {
    topic: 'Hip replacement',
    lang: 'en',
    date: '15/02/22',
    time: '16:30–18:30',
    room: '1.5.10',
    prompts: [
      'How can we effectively prepare patients for the procedure?',
    ],
    papers: [
      {
        title: 'Hip replacement',
        url: 'https://doi.org/10.1016/s0140-6736(18)31777-x',
      },
    ],
    archived: true,
  },
  {
    topic: 'Reemplazo de cadera',
    lang: 'es',
    date: '22/02/22',
    time: '16:30–18:30',
    room: '1.5.10',
    prompts: [
      '¿Cómo podemos preparar a los pacientes para la operación de forma eficaz?',
    ],
    papers: [
      {
        title: 'Hip replacement',
        url: 'https://doi.org/10.1016/s0140-6736(18)31777-x',
      },
    ],
    archived: true,
  },
  {
    topic: 'Coronary artery disease',
    lang: 'en',
    date: '08/03/22',
    time: '16:30–18:30',
    room: '1.5.10',
    archived: true,
  },
  {
    topic: 'Arteriopatía coronaria',
    lang: 'es',
    date: '15/03/22',
    time: '16:30–18:30',
    room: '1.5.10',
    archived: true,
  },
  {
    topic: 'Migraña',
    lang: 'es',
    date: '04/05/23',
    time: '10:30–12:30',
    room: '1.6.4 (EPS)',
    archived: true,
  },
  {
    topic: 'Tendinopatía de Aquiles',
    lang: 'es',
    date: 'Septiembre 2023',
    time: 'Hora pendiente',
    room: 'Aula pendiente',
    archived: false,
  },
  {
    topic: 'Parálisis cerebral',
    lang: 'es',
    date: 'Octubre 2023',
    time: 'Hora pendiente',
    room: 'Aula pendiente',
    archived: false,
  },
  {
    topic: 'Artritis reumatoide',
    lang: 'es',
    date: 'Noviembre 2023',
    time: 'Hora pendiente',
    room: 'Aula pendiente',
    archived: false,
  },
  {
    topic: 'Desgarro del LCA',
    lang: 'es',
    date: 'Diciembre 2023',
    time: 'Hora pendiente',
    room: 'Aula pendiente',
    archived: false,
  },
];
